[package]
name = "rust_etl"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
diesel = { version = "2.0.0", features = ["postgres"] }
serde = "1.0.210"
serde_json = "1.0.128"
serde_derive = "1.0.210"
